project:
  type: website

website:
  title: albertprofe wiki
  #cookie-consent:
  #  type: express
  #  style: headline
  #  palette: dark

  repo-url: https://github.com/Albertprofe/wiki
  repo-actions: [edit, issue]

  navbar:
    background: dark
    style: "floating"
    search: true
    
    right:
      - text: Home
        file: index.qmd
      - sidebar:linux
      - sidebar:markup
      - sidebar:javase
      - sidebar:spring   
      - sidebar:reactjs
      - sidebar:scrum
      - sidebar:devops
      - sidebar:vocabulary
      - sidebar:ifcd
      - sidebar:about

  sidebar:
    - id: "devops"
      title: "DevOps"
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents:
        - text: "DevOps"
        - text: "---"  
        - section: "What is DevOps"
          contents: 
            - devops/devops-what-intro.qmd
            - devops/devops-what-overview.qmd
            - devops/devops-what-immutable.qmd
        - text: "---"  
        - section: "Documentation"
          contents: 
            - devops/devops-doc-quarto.qmd
        - text: "---"  
        - section: "Version Control"
          contents: 
            - devops/devops-vc-git.qmd
            - devops/devops-vc-github.qmd
        - text: "---" 
        - section: "IDEs"
          contents: 
            - devops/devops-ide-visualcode.qmd
            - devops/devops-ide-intelljidea.qmd
        - text: "---"           
        - section: "DevOps tools"
          contents:
            - devops/devops-tools-aws.qmd 
            - devops/devops-tools-docker.qmd
            - devops/devops-tools-jenkins.qmd
            - devops/devops-tools-k8s.qmd
            - devops/devops-tools-digitalocean.qmd
            - devops/devops-tools-installjenkins.qmd
            - devops/devops-tools-installmaven.qmd
        - text: "---"      
        - section: "DevOps Laboratories"
          contents: 
            - devops/devops-lab-chatapp.qmd
            - devops/devops-lab-springbooksintro.qmd
            - devops/devops-lab-springbookss3.qmd
            - devops/devops-lab-springbooksdocker.qmd
            - devops/devops-lab-k8sdigitalocean.qmd
        - text: "---"  
        - section: "DevOps readings"
          contents: 
            - devops/resources.qmd

    - id: "linux"
      title: "Linux OS"
      contents: 
        - text: "Linux OS"
        - text: "---"  
        - section: "Linux: concepts"
          contents: 
            - linux/linux-what-basics.qmd
            - linux/linux-what-sudo.qmd
            - linux/linux-what-pipes.qmd
            - linux/linux-what-filesys.qmd
            - linux/linux-what-vm.qmd
        - text: "---"  
        - section: "Linux: distros"
          contents: 
            - linux/linux-distros-ubuntu.qmd
            - linux/linux-distros-mint.qmd
            - linux/linux-distros-debian.qmd
            - linux/linux-distros-opensuse.qmd
            - linux/linux-distros-manjaro.qmd
            - linux/linux-distros-redhat.qmd
        - text: "---"  
        - section: "Linux: laboratories"
          contents: 
            - linux/lilab01-1.qmd
            - linux/lilab01-2.qmd
            - linux/lilab01-3.qmd
            - linux/lilab02-1.qmd
            - linux/lilab03-1.qmd
            - linux/lilab03-2.qmd
            - linux/lilab03-3.qmd
            - linux/lilab03-4.qmd
        - text: "---"  
        - section: "Linux readings"
          contents: 
            - linux/resources.qmd
     
    - id: "markup"
      title: "MarkUp"
      contents: 
        - text: "MarkUp Languages and Styling"
        - text: "---"  
        - section: "MarkUp Languages"
          contents: 
            - markup/markup-lang-intro.qmd
            - markup/markup-lang-html.qmd
            - markup/markup-land-md.qmd
            - markup/markup-lang-htmlmd.qmd
        - text: "---"  
        - section: "Quarto Markdown"
          contents: 
            - markup/markup-quarto-basics.qmd
            - markup/markup-quarto-create.qmd
            - markup/markup-quarto-publish.qmd
            - markup/markup-quarto-code.qmd
            - markup/markup-quarto-cheatsheet.qmd
        - text: "---"  
        - section: "Styling: CSS"
          contents: 
            - markup/markup-css-basics.qmd
            - markup/markup-css-w3css.qmd
        - text: "---"  
        - section: "MarkUp Languages Laboratories"
          contents: 
            - markup/mulab1.qmd
        - text: "---" 
        - section: "MarkUp Languages readings"
          contents: 
            - markup/resources.qmd
            
    - id: "scrum"
      title: "SCRUM"
      contents: 
        - text: "SCRUM"
        - text: "---"  
        - section: "What is SCRUM"
          contents: 
            - scrum/scrum.qmd
            - scrum/agilemanifesto.qmd
            - scrum/scrumguide.qmd
            - scrum/digitaltoolsscrum.qmd
        - text: "---"  
        - section: "Weeks"
          contents: 
            - scrum/week1.qmd
            - scrum/week2.qmd
            - scrum/week3.qmd
            - scrum/week4.qmd
            - scrum/week5.qmd
 
    - id: "javase"
      title: "Java SE"
      contents: 
        - text: "Java Standard Edition"
        - text: "---"  
        - section: "What is Java SE"
          contents: 
            - javase/se-what-basics.qmd
            - javase/se-what-principles.qmd
            - javase/se-what-moochelsinki.qmd
        - text: "---"
        - section: "Java Concepts"
          contents:
            - javase/se-concepts-maven.qmd
            - javase/se-concepts-createproject.qmd
            - javase/se-concepts-projectgit.qmd
            - javase/se-concepts-tdd.qmd
            - javase/se-concepts-objects.qmd
            - javase/se-concepts-scope.qmd
            - javase/se-concepts-static.qmd
            - javase/se-concepts-coupling.qmd
            - javase/se-concepts-package.qmd
        - text: "---"
        - section: "Java Principles"
          contents:
            - javase/se-principles-encapsulation.qmd
            - javase/se-principles-abstraction.qmd
            - javase/se-principles-inheritance.qmd
            - javase/se-principles-polymorphism.qmd    
        - text: "---"  
        - section: "Java Design Patterns"
          contents: 
            - javase/se-pattern-intro.qmd
            - javase/se-pattern-uml.qmd
            - javase/se-pattern-singleton.qmd
            - javase/se-pattern-factory.qmd
            - javase/se-pattern-abstractfactory.qmd
            - javase/se-pattern-observer.qmd
            - javase/se-pattern-builder.qmd
        - text: "---"  
        - section: "Java SE Laboratories"
          contents: 
            - javase/selab1-1.qmd
            - javase/selab1-2.qmd
            - javase/selab3.qmd
            - javase/selab4.qmd
            - javase/selab5.qmd
        - text: "---" 
        - section: "Java SE readings"
          contents: 
            - javase/resources.qmd

    - id: "spring"
      title: "Spring"
      contents:
        - text: "Spring"
        - text: "---"  
        - section: "Spring Legacy"
          contents: 
            - spring/spring.qmd
            - spring/springmvc.qmd
        - text: "---"  
        - section: "Spring Boot"
          contents: 
            - springboot/springboot.qmd
        - text: "---"  
        - section: "Spring Boot Laboratories"
          contents: 
            - springboot/sblab1.qmd
            - springboot/sblab2.qmd
            - springboot/sblab3.qmd
            - springboot/sblab4.qmd
            - springboot/sblab5.qmd
        - text: "---" 
        - section: "Spring Boot readings"
          contents: 
            - springboot/resources.qmd
        
    - id: "reactjs"
      title: "React JS"
      contents: 
        - text: "React JS"
        - text: "---"  
        - section: "React JS Principles"
          contents: 
            - reactjs/reactjs.qmd
        - section: "React JS Hooks"
          contents: 
            - reactjs/hookstate.qmd
            - reactjs/hookreducer.qmd
            - reactjs/hookref.qmd
            - reactjs/hookeffect.qmd
            - reactjs/hookcustom.qmd
        - text: "---"  
        - section: "Context and Provider"
          contents: 
            - reactjs/reactjscontext.qmd
        - text: "---"  
        - section: "React JS Laboratories"
          contents: 
            - reactjs/rjslab1.qmd
            - reactjs/rjslab2.qmd
            - reactjs/rjslab3.qmd
            - reactjs/rjslab4.qmd
            - reactjs/rjslab5.qmd
        - text: "---" 
        - section: "React JS readings"
          contents: 
            - reactjs/resources.qmd

    
    - id: "ifcd"
      title: "IFCD0210"
      contents: 
        - text: "IFCD0210"
        - text: "---"  
        - section: "Web App IFCD0210"
          contents: 
            - ifcd0210/ifcd0210.qmd
            - ifcd0210/ifcd0210calendar.qmd  
            - ifcd0210/ifcd0210initemail.qmd  
            - ifcd0210/ifcd0210deliveries.qmd  
        
    - id: "vocabulary"
      title: "Vocabulary"
      contents: 
        - text: "Vocabulary"
        - text: "---"  
        - section: "General Vocabulary"
          contents: 
            - vocabulary/vocabgeneral.qmd
            - vocabulary/vocabscrum.qmd
            - vocabulary/vocabdevops.qmd
        - text: "---"  
        - section: "Back-end Vocabulary"
          contents: 
            - vocabulary/vocabjava.qmd
            - vocabulary/vocabspringboot.qmd
            - vocabulary/vocabdatabase.qmd
        - text: "---"  
        - section: "Front-end Vocabulary"
          contents: 
            - vocabulary/vocabreactjs.qmd 
            - vocabulary/vocabweb.qmd          

    - id: "about"
      title: "About"
      contents: 
        - text: "About"
        - text: "---"  
        - section: "About"
          contents: 
            - about/aboutme.qmd
            - about/aboutthissite.qmd
            - about/aboutlearning.qmd
            - about/aboutimagescredit.qmd 
            - about/aboutquestions.qmd
            - about/aboutlisting.qmd                 
  
  
  page-footer: 
    background: dark
    left: "[Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)" 
    center: "if you want to go far, walk slow" 
    right: 
      - icon: github
        href: https://github.com/AlbertProfe/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    fontsize:  "1.0em"
    theme:
      light: default
      dark: superhero
    css: styles.css
    toc: true
    toc-depth: 5
    email-obfuscation: javascript
    
execute:
  cache: true
  freeze: true




