---
title: "IFCT116 Official Docs"
categories: [ifct166, training] 
---

## Identificació del Certificat de Professionalitat
- Denominació: **FHERRAMIENTAS DEVOPS**
- Codi: **IFCt166exp**
- Hores: 75h
- Família professional: Informàtica i comunicacions
- Àrea professional: SISTEMAS Y TELEMÁTICA
- Nivell de qualificació professional: 3


## Documentació


- [PROGRAMA Formatiu: Fullstack júnior web developer amb Java](/images/ifct166-24/IFCT116EXP.pdf){#ifct166-fitxa}




## Programa formatiu

- Módulo 1: Introducción a DevOps
- Módulo 2: Contenedores con Docker
- Módulo 3: Infraestructura como Código
- Módulo 4: Gestion de la configuración con Ansible
- Módulo 5: Infraestructura Inmutable
- Módulo 6: Integración y Entrega Continua con Jenkins


## Competència general

> Dominar las principales herramientas de DevOps para lograr la automatización de todos los pasos de la construcción del software, desde la integración, las pruebas y la entrega hasta el despliegue y la administración de la Infraestructura

